# Generated by Django 4.0.4 on 2022-06-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('logo', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Estabelecimento',
            },
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prod', models.CharField(default=None, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('fitness_food', models.BooleanField(default=False)),
                ('brazilian_food', models.BooleanField(default=False)),
                ('chinese_food', models.BooleanField(default=False)),
                ('japanese_food', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('fast_food', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('cake_or_pie', models.BooleanField(default=False)),
                ('salad', models.BooleanField(default=False)),
                ('price', models.CharField(default=None, max_length=5)),
                ('estabelecimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.estabelecimento')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
